---
version: '3.7'
services:
  mysql:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: time_recorder
    ports:
      - '3306:3306'
    expose:
      - '3306'
